# Generated by Django 3.0 on 2019-12-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191124_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverydetailsmodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='deliverydetailsmodel',
            name='postal_code',
        ),
        migrations.AlterField(
            model_name='deliverydetailsmodel',
            name='address',
            field=models.TextField(max_length=300),
        ),
    ]
